pool:
  name: 'Azure Pipelines'

steps:

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'absolute-donkey-aks-azdo-1708894828939'
    namespace: 'ian'
    command: 'run'
    arguments: 'bboard --namespace=ian --image=ianlutzker/node-bulletin-board'
    # secretType: 'dockerRegistry'
    # containerRegistryType: 'Azure Container Registry'