pool:
  name: 'Azure Pipelines'

steps:

- checkout: none

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'absolute-donkey-aks-azdo-1708894828939'
    namespace: 'azdo'
    command: 'run'
    arguments: 'bboard --image=ianlutzker/node-bulletin-board --port=80'
    # secretType: 'dockerRegistry'
    # containerRegistryType: 'Azure Container Registry'